[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["paul <pkavule@gmail.com>"]
readme = "README.md"
packages = [{include = "app", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
